Repository bvcms/bvcms, pull requests merged in 2018-08, with the labels that each got.

#225 Austin allowed fund dynamic role
  CmsData/API/APIContributionSearchModel.cs
  CmsData/CmsData.csproj
  CmsData/Extensions/ContributionFundExtensions.cs
  CmsData/Generated/ContributionFund.cs
  CmsData/Migrations/20180720_StoredProcedure_CHAIDonationsReport2.sql
  CmsData/Migrations/20180720_StoredProcedure_GetDepositDateTotalsUsingAuthorizedFunds.sql
  CmsData/Migrations/20180720_Table_ContributionFunds.sql
  CmsWeb/Areas/Finance/Controllers/FinanceReportsController.cs
  CmsWeb/Areas/Finance/Controllers/FundController.cs
  CmsWeb/Areas/Finance/Models/DepositTotalsModel.cs
  CmsWeb/Areas/Finance/Models/TotalsByFundAgeRangeModel.cs
  CmsWeb/Areas/Finance/Models/TotalsByFundModel.cs
  CmsWeb/Areas/Finance/Models/TotalsByFundRange.cs
  CmsWeb/Areas/Finance/Views/Fund/Edit.cshtml
  CmsWeb/Code/CodeInfo.cs
  CmsWeb/Code/CodeValueList.cs
  CmsWeb/Code/CodeValueModel.cs
Labels: client-request, db-schema-changes, enhancement

#227 Change order for dropdown to be based off of fund name. This only affects these dropdowns.
  CmsWeb/Areas/Finance/Models/BundleModel.cs
Labels: client-request

#232 another list of funds to make alphabetical
  CmsWeb/Areas/Finance/Controllers/PostBundleController.cs
  CmsWeb/Areas/Finance/Models/BundleModel.cs
  CmsWeb/Areas/Finance/Models/PostBundleModel.cs
Labels: client-request

#224 Send group leader attendance messages
  CmsData/Classes/Twilio/TwilioHelper.cs
  CmsData/CmsData.csproj
  CmsData/Email/Emailer.cs
  CmsData/Generated/Organization.cs
  CmsData/Migrations/20180719_send-attendance-link.sql
  CmsWeb/Areas/Org/Models/Org/SettingsAttendanceModel.cs
  CmsWeb/Areas/Org/Views/Org/Settings/AttendanceEdit.cshtml
  DbmlBuilder/DbmlBuilder/CodeGeneration/Templates/CS_ContextTemplate.aspx
  DbmlBuilder/DbmlBuilder/CodeGeneration/Templates/CS_EntityTemplate.aspx
  DbmlBuilder/DbmlBuilder/CodeGeneration/Templates/CS_TableFunctionTemplate.aspx
  DbmlBuilder/DbmlBuilder/Program.cs
  SqlScripts/BuildDb/Creating_dbo_Organizations.sql
Labels: client-request, enhancement
